### ISSUE TITLE
searchFiled 添加 multiple select 、TreeSelect、DatePicker 的支持

### ISSUE THREAD

**Issue by gdcnb** [NewbeeFE/antd-data-table#3]

**Comment by djyde** [comment]
multiple select 可以用自带的 select renderer, 只要 payload 里面的 props 传 `multiple` 就行（和 ant-design）一致。

**Comment by djyde** [comment]
- [ ] TreeSelect
- [ ] DatePicker

**Comment by djyde** [comment]
0.1.4 已支持
