### ISSUE TITLE
searchField 的FormItem 支持垂直布局和水平布局的配置 和支持 width 的配置

### ISSUE THREAD

**Issue by gdcnb** [NewbeeFE/antd-data-table#6]

**Comment by djyde** [comment]
这个 issue 表达不是很清晰，说明一下你要的效果。方便别人贡献以及查找问题。

**Comment by gdcnb** [comment]
1. 目前 searchField 的内容区的操作项 label 和 输入项只能是水平布局，希望添加对操作项布局的配置，由业务方来操作是水平布局还是垂直布局
2. 目前 searchField 的操作项是固定宽度的，希望可以支持自定义宽度的配置
